#!/bin/bash -eux
wget -q -O media/advocate.jpg https://o.quizlet.com/dCt7tNLolgMmXXtC0nyFug_m.jpg
wget -q -O media/commission.jpg https://o.quizlet.com/YG8Mhm7fpfQ4mDJkp-az.g_m.jpg
wget -q -O media/comprise.png https://o.quizlet.com/CgFb7EihgwvTYlZ3AXO3bA_m.png
wget -q -O media/confine.jpg https://o.quizlet.com/i/6zRHBaLCs9pi6eNcoV-AHw_m.jpg
wget -q -O media/consent.jpg https://o.quizlet.com/i/qKuwXuUmA2syD1GxAP2Q3w_m.jpg
wget -q -O media/contend.png https://o.quizlet.com/PA3idxFDz.DOYHEp65FEwg_m.png
wget -q -O media/controversy.jpg https://o.quizlet.com/i/mpGgQub6CJvWpXdamm8Lzw_m.jpg
wget -q -O media/devastate.jpg https://farm8.staticflickr.com/7195/6829468522_138cfdc263_m.jpg
wget -q -O media/dispute.jpg https://o.quizlet.com/f.SHhLTfZxU8lPpbXhba6g_m.jpg
wget -q -O media/disrupt.jpg https://o.quizlet.com/n1ZVhbLRJYBGOnmwTTfQ5w_m.jpg
wget -q -O media/elaborate.jpg https://farm3.staticflickr.com/2469/3931354773_3465ff2520_m.jpg
wget -q -O media/endorse.jpg https://farm8.staticflickr.com/7165/6549277915_172595e0dd_m.jpg
wget -q -O media/excess.jpg https://farm6.staticflickr.com/5099/5531402433_c426c05515_m.jpg
wget -q -O media/facilitate.jpg https://farm1.staticflickr.com/43/90811910_4bd1985f37_m.jpg
wget -q -O media/foster.jpg https://o.quizlet.com/i/CH2FHdm2wVHugAcqrC8JYQ_m.jpg
wget -q -O media/gaze.jpg https://o.quizlet.com/g6tgb.6ULM9qTQ7qWaWEMw_m.jpg
wget -q -O media/grain.jpg https://farm3.staticflickr.com/2555/3842334310_0d2c428fc7_m.jpg
wget -q -O media/harsh.jpg https://o.quizlet.com/r8s5LB.LGcFZlB8V7R6iEA_m.jpg
wget -q -O media/hostile.jpg https://farm8.staticflickr.com/7129/7427611434_d53aac46cc_m.jpg
wget -q -O media/implicate.jpg https://o.quizlet.com/BkkQf0V7T8hZFKtyPcXkMw_m.jpg
wget -q -O media/impose.jpg https://o.quizlet.com/4RdQppUsmlxnz4NtRIJ.Hw_m.jpg
wget -q -O media/lodge.jpg https://o.quizlet.com/U6t4IeGHTgaCQtW8JAQ.rA_m.jpg
wget -q -O media/moderate.jpg https://o.quizlet.com/Wy9vrAEV4UaPgEpEDDqWDw_m.jpg
wget -q -O media/modest.jpg https://o.quizlet.com/bgfuCbZWDxk6EMVnX3wa9w_m.jpg
wget -q -O media/narrate.jpg https://o.quizlet.com/P2hxt9pcz3Lto9wCoCF89Q_m.jpg
wget -q -O media/oblige.jpg https://farm1.staticflickr.com/48/143084796_8fe04da177_m.jpg
wget -q -O media/persuade.jpg https://o.quizlet.com/i/UprVnH_hkzWWGx17hwyvfQ_m.jpg
wget -q -O media/premise.jpg https://o.quizlet.com/8GABUqCMxaQwDSwsjODPoA_m.jpg
wget -q -O media/profound.jpg https://farm5.staticflickr.com/4021/4283684892_f7fe5f80af_m.jpg
wget -q -O media/prosper.jpg https://o.quizlet.com/p61HNNAApRCM.NmX2gQgtQ_m.jpg
wget -q -O media/pursue.jpg https://o.quizlet.com/i/YdanrSbxIlW6JLBAuFsLEA_m.jpg
wget -q -O media/restrain.jpg https://o.quizlet.com/i/n7JBMMONg1VFTwGl9UyaMQ_m.jpg
wget -q -O media/retain.jpg https://o.quizlet.com/yrODx3uUqMkdx9Z3gdRpmw_m.jpg
wget -q -O media/revise.jpg https://o.quizlet.com/AvHNYZGTg5cClos0NsZeNw_m.jpg
wget -q -O media/seize.jpg https://farm4.staticflickr.com/3145/2850198138_ab671f0967_m.jpg
wget -q -O media/sigh.jpg https://o.quizlet.com/amfgblbJNnmEoOHkLt75eA_m.jpg
wget -q -O media/squeeze.jpg https://farm6.staticflickr.com/5251/5389756390_798369a3c7_m.jpg
wget -q -O media/strain.jpg https://farm4.staticflickr.com/3380/3515336395_0976e88393_m.jpg
wget -q -O media/stun.jpg https://o.quizlet.com/eRA1zQvIDCDGZN7lqmeIbw_m.jpg
wget -q -O media/supplement.jpg https://o.quizlet.com/i/M2x6yZ3ILAM3RMUb90uX9g_m.jpg
wget -q -O media/tackle.jpg https://farm3.staticflickr.com/2317/2486054320_e6434d7fef_m.jpg
wget -q -O media/undergo.jpg https://o.quizlet.com/Fh8zczK7JwvUyo9Q.dZ0Ng_m.jpg
wget -q -O media/undertake.jpg https://o.quizlet.com/7JXTJNycLBfSu7MMyKEXtA_m.jpg
